In [1]:
def det_rec(A):
    from copy import deepcopy
    n = len(A)
    
    if n == 2:
        res = A[0][0]*A[1][1] - A[0][1]*A[1][0]
        return res
    
    res = 0
    for i in range(n):
        X = deepcopy(A)
        X = X[1:]
        nx = len(X)
        for j in range(nx):
            X[j] = X[j][:i] + X[j][i+1:]
        sign = (-1) ** (i%2)
        sub_det = det_rec(X)
        res += sub_det * sign * A[0][i]
    return res

def transpose(A):
    n = len(A)
    m = len(A[0])
    res = []
    for j in range(m):
        row = []
        for i in range(n):
            val = A[i][j]
            row.append(val)
        res.append(row)
    return res

def scalar_mul(a, A):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = a * A[i][j]
            row.append(val)
        res.append(row)
    return res


# calculating inverse matrix *****

def inv(A):
    n = len(A)

    if n == 2:
        res = [[-A[1][1],A[0][1]],[A[1][0],-A[0][0]]]
        return res
          
    C = []    
    for i in range(n):
        c_row = []
        idx = list(range(0,n))
        idx.remove(i)
        for j in range(n):
            X = []
            for k in idx:
                val = A[k][:j]+A[k][j+1:]
                X.append(val)
                Mij = det_rec(X)
                Cij = Mij * (-1)**(i+j)
            c_row.append(Cij)
        C.append(c_row)

    adj = transpose(C)
    detA = det_rec(A)
    res = scalar_mul(1/detA, adj)
    return res

In [76]:
import numpy as np

A = np.array([[3,2,0],[-1,-3,6],[2,3,-5]])
inv_A = np.linalg.inv(A)
print(inv_A)

[[-0.6  2.   2.4]
 [ 1.4 -3.  -3.6]
 [ 0.6 -1.  -1.4]]
