# Vector

In [6]:
# vector addition
def v_add(u, v):
    n = len(u)
    w = []
    for i in range(n):
        val = u[i] + v[i]
        w.append(val)
    return w

# vector subtraction
def v_subtract(u, v):
    n = len(u)
    w = []
    for i in range(n):
        val = u[i] -  v[i]
        w.append(val)
    return w

# vector & scalar multiplication
def scalar_v_mul(a, v):
    n = len(v)
    w = []
    for i in range(n):
        val = a * v[i]
        w.append(val)
    return w

# vector element multiplication
def v_mul(u, v):
    n = len(u)
    w = []
    for i in range(n):
        val = u[i] * v[i]
        w.append(val)
    return w

# vector element division
def v_div(u, v):
    n = len(u)
    w = []
    for i in range(n):
        val = u[i] / v[i]
        w.append(val)
    return w

In [23]:
import numpy as np

u = np.array([1,2,3])
v = np.array([4,5,6])
print(f"u = {u}")
print(f"v = {v}\n\n")
print(f"u + v = {u + v}\n")
print(f"u - v = {u - v}\n")
print(f"3 * v = {3 * v}\n")
print(f"u * v = {u * v}\n")
print(f"u / v = {u / v}")

u = [1 2 3]
v = [4 5 6]


u + v = [5 7 9]

u - v = [-3 -3 -3]

3 * v = [12 15 18]

u * v = [ 4 10 18]

u / v = [0.25 0.4  0.5 ]


# Matrix

In [53]:
# matrix addition
def add(A, B):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = A[i][j] + B[i][j]
            row.append(val)
        res.append(row)
    return res

# matrix subtraction
def subtract(A, B):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

# matrix scalar multiplication
def scalar_mul(a, A):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = a * A[i][j]
            row.append(val)
        res.append(row)
    return res

# matrix element multiplication
def ele_product(A, B):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = A[i][j] * B[i][j]
            row.append(val)
        res.append(row)
    return res

# matrix multiplication*****
def matmul(A, B):
    m = len(A)
    r = len(A[0]) # r = len(B)
    n = len(B[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = 0
            for k in range(r):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

# Using Numpy Module

In [32]:
import numpy as np
A = np.array([[2,7],[3,4],[5,6]])
B = np.array([[1,4],[4,-1],[2,5]])

print(f"A = \n{A}")
print(f"B = \n{B}\n\n")

print(f"A + B = \n{A + B}\n")
print(f"A - B = \n{A - B}\n")
print(f"3 * A = \n{3 * A}\n")
print(f"np.multiply(A,B) = \n{np.multiply(A,B)}\n")

A = 
[[2 7]
 [3 4]
 [5 6]]
B = 
[[ 1  4]
 [ 4 -1]
 [ 2  5]]


A + B = 
[[ 3 11]
 [ 7  3]
 [ 7 11]]

A - B = 
[[ 1  3]
 [-1  5]
 [ 3  1]]

3 * A = 
[[ 6 21]
 [ 9 12]
 [15 18]]

np.multiply(A,B) = 
[[ 2 28]
 [12 -4]
 [10 30]]



In [9]:
import numpy as np

A = np.array([[2,7],[3,4],[5,2]])
B = np.array([[3,-3,5],[-1,2,-1]])

print(f"A = \n{A}")
print(f"B = \n{B}\n\n")

print(f"np.matmul(A,B) = \n{np.matmul(A,B)}")

A = 
[[2 7]
 [3 4]
 [5 2]]
B = 
[[ 3 -3  5]
 [-1  2 -1]]


np.matmul(A,B) = 
[[ -1   8   3]
 [  5  -1  11]
 [ 13 -11  23]]
