In [9]:
# tensor

T = [[[1,2],[3,4]],[[5,6],[7,8]]] #2✕2✕2 tensor 
print(T)
print(T[0][0][0])
print(T[1][0][1])
print(T[0][1][1])

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
1
6
4


In [20]:
# norm of tensor

A = [[[1,0,1,0],[2,1,0,1],[3,4,0,2]],[[3,1,2,0],[1,0,4,2],[0,1,0,2]]] #2✕3✕4 tensor 

n = len(A[0])
p = len(A[0][0])
q = len(A)

norm = 0
for i in range(n):
    for j in range(p):
        for k in range(q):
            norm += A[k][i][j]**2
norm = norm ** 0.5
print(f"Norm(A) = {norm}")

Norm(A) = 8.774964387392123


In [52]:
# inner product of tensor

A = [[[1,0,1,0],[2,1,0,1],[3,4,0,2]],[[3,1,2,0],[1,0,4,2],[0,1,0,2]]]
B = [[[2,1,3,1],[0,2,1,3],[1,0,1,1]],[[1,2,3,1],[3,1,0,3],[0,2,3,1]]]

n = len(A[0])
p = len(A[0][0])
q = len(A)

inner_product = 0
for i in range(n):
    for j in range(p):
        for k in range(q):
            inner_product += A[k][i][j]*B[k][i][j]
print(f"inner_product = {inner_product}")


# inner product using Numpy
import numpy as np

C = np.multiply(A,B)
inner_p = 0
for i in range(len(C)):
    for j in range(len(C[0])):
        for k in range(len(C[0][0])):
            inner_p += C[i][j][k]
print(inner_p)

inner_product = 39
39


In [69]:
# matricization

A = [[[1,4,7,10],[2,5,8,11],[3,6,9,12]],[[13,16,19,22],[14,17,20,23],[15,18,21,24]]] #2✕3✕4 tensor 

n = len(A[0])
p = len(A[0][0])
q = len(A)

# mode-1 matricization
mode1 = []
for i in range(n):
    row = []
    for j in range(q):
        for k in range(p):
            row.append(A[j][i][k])
    mode1.append(row)
print(mode1)

# mode-2 matricization
mode2 = []
for i in range(p):
    row = []
    for j in range(q):
        for k in range(n):
            row.append(A[j][k][i])
    mode2.append(row)
print(mode2)

# mode-3 matricization
mode3 = []
for i in range(q):
    row = []
    for j in range(p):
        for k in range(n):
            row.append(A[i][k][j])
    mode3.append(row)
print(mode3)


# matricization using Numpy
import numpy as np

A = np.array([[[1,4,7,10],[2,5,8,11],[3,6,9,12]],[[13,16,19,22],[14,17,20,23],[15,18,21,24]]]) #2✕3✕4 tensor

# mode-1 matricization
mode_1 = np.concatenate((A[0],A[1]), axis=1)
print(mode_1)
# mode-2 matricization
mode_2 = np.concatenate((A[0].T, A[1].T), axis=1)
print(mode_2)
# mode-2 matricization
A0 = A[0].reshape(-1)
A1 = A[1].reshape(-1)
mode_3 = np.concatenate((A0,A1), axis=0).reshape(2,-1)
print(mode_3)

[[1, 4, 7, 10, 13, 16, 19, 22], [2, 5, 8, 11, 14, 17, 20, 23], [3, 6, 9, 12, 15, 18, 21, 24]]
[[1, 2, 3, 13, 14, 15], [4, 5, 6, 16, 17, 18], [7, 8, 9, 19, 20, 21], [10, 11, 12, 22, 23, 24]]
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]
[[ 1  4  7 10 13 16 19 22]
 [ 2  5  8 11 14 17 20 23]
 [ 3  6  9 12 15 18 21 24]]
[[ 1  2  3 13 14 15]
 [ 4  5  6 16 17 18]
 [ 7  8  9 19 20 21]
 [10 11 12 22 23 24]]
[[ 1  4  7 10  2  5  8 11  3  6  9 12]
 [13 16 19 22 14 17 20 23 15 18 21 24]]


In [71]:
# tensor product

U = [[1,3,5],[2,4,6]] #2✕3 matrix 
A = [[[1,4,7,10],[2,5,8,11],[3,6,9,12]],[[13,16,19,22],[14,17,20,23],[15,18,21,24]]] #2✕3✕4 tensor 

tensor_product = []
for t in range(len(A)):
    matrix = []
    for i in range(len(U)):
        row = []
        for q in range(len(A[0][0])):
            val = 0
            for j in range(len(U[0])):
                val += U[i][j] * A[t][j][q]
            row.append(val)
        matrix.append(row)
    tensor_product.append(matrix)
    
print(tensor_product)


# tensor product using numpy
import numpy as np

U = [[1,3,5],[2,4,6]] #2✕3 matrix 
A = [[[1,4,7,10],[2,5,8,11],[3,6,9,12]],[[13,16,19,22],[14,17,20,23],[15,18,21,24]]] #2✕3✕4 tensor

UA1 = np.matmul(U, A[0])
UA2 = np.matmul(U, A[1])
tensor_p = np.concatenate((UA1, UA2), axis=0).reshape(2,2,4)
print(tensor_p)

[[[22, 49, 76, 103], [28, 64, 100, 136]], [[130, 157, 184, 211], [172, 208, 244, 280]]]
[[[ 22  49  76 103]
  [ 28  64 100 136]]

 [[130 157 184 211]
  [172 208 244 280]]]
