In [12]:
def matmul(A, B):
    m = len(A)
    r = len(A[0]) # r = len(B)
    n = len(B[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = 0
            for k in range(r):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

def identity(n):
    I = []
    for i in range(n):
        row = []
        for j in range(n):
            if i != j:
                val = 0
                row.append(val)
            else:
                val = 1
                row.append(val)
        I.append(row)
    return I

def transpose(A):
    n = len(A)
    m = len(A[0])
    res = []
    for j in range(m):
        row = []
        for i in range(n):
            val = A[i][j]
            row.append(val)
        res.append(row)
    return res

def norm(a):
    n = len(a)
    res = 0
    for i in range(n):
        res += a[i]**2
    res = res**(0.5)
    return res

def inner_product(a,b):
    n = len(a) # n=len(a)=len(b)
    res = 0
    for i in range(n):
        res += a[i]*b[i]
    return res

def normalize(a):
    n = len(a)
    res = []
    for i in range(n):
        val = a[i] / norm(a)
        res.append(val)
    return res

def qr_gram(A):
    At = transpose(A)
    n = len(At)
    norm_list = []
    U = []
    V = []

    for i in range(0,n):
        if i == 0:
            u = At[i]
            U.append(u)
            norm_u = norm(u)
            norm_list.append(norm_u)

        else:
            a = At[i]
            dp_list = []
            for j in range(0,i):
                dp = inner_product(a,U[j])
                dp_list.append(dp)

            u = []
            for j in range(0,n):
                val = a[j]
                for k in range(0, i):
                    val -= (dp_list[k] / norm_list[k]**2)*U[k][j]
                u.append(val)
            norm_u = norm(u)
            norm_list.append(norm_u)
            U.append(u)

        v = normalize(u)
        V.append(v)
    Q = transpose(V)

    R = []
    for i in range(0,n):
        r = []
        for j in range(0,n):
            if i > j:
                val = 0
                r.append(val)
            else:
                val = inner_product(At[j], V[i])
                r.append(val)
        R.append(r)
        
    return Q, R

In [40]:
# eigenvector and eigenvalue using QR-decomposition
# only when matrix A is symmetric...

from copy import deepcopy

def eig_qr(A):
    V = identity(len(A))
    for i in range(0,30):
        if i == 0:
            Ai = deepcopy(A)
        else:
            Ai = Ap
        Q, R = qr_gram(Ai)
        Ap = matmul(R,Q)
        V = matmul(V,Q)
        
    E = []
    for i in range(len(Ap)):
        E.append(Ap[i][i])
    return E, V #E=eigenvalue, V=eigenvector

In [38]:
# eigenvector and eigenvalue using QR-decomposition using numpy

import numpy as np
A = np.array([[3,2,1],[2,1,4],[1,4,2]])
e, v = np.linalg.eig(A)
print(f"Eigenvalue = {e}")
print(f"Eigenvector =\n {v}")

Eigenvalue = [ 6.71297995  1.95454118 -2.66752113]
Eigenvector =
 [[ 0.49473045  0.85407884  0.16059614]
 [ 0.60797565 -0.20810216 -0.76619782]
 [ 0.62097294 -0.47669994  0.62221361]]
