In [10]:
def matmul(A, B):
    m = len(A)
    r = len(A[0]) # r = len(B)
    n = len(B[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            val = 0
            for k in range(r):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

def identity(n):
    I = []
    for i in range(n):
        row = []
        for j in range(n):
            if i != j:
                val = 0
                row.append(val)
            else:
                val = 1
                row.append(val)
        I.append(row)
    return I

def transpose(A):
    n = len(A)
    m = len(A[0])
    res = []
    for j in range(m):
        row = []
        for i in range(n):
            val = A[i][j]
            row.append(val)
        res.append(row)
    return res

def norm(a):
    n = len(a)
    res = 0
    for i in range(n):
        res += a[i]**2
    res = res**(0.5)
    return res

def inner_product(a,b):
    n = len(a) # n=len(a)=len(b)
    res = 0
    for i in range(n):
        res += a[i]*b[i]
    return res

def normalize(a):
    n = len(a)
    res = []
    for i in range(n):
        val = a[i] / norm(a)
        res.append(val)
    return res

def qr_gram(A):
    At = transpose(A)
    n = len(At)
    norm_list = []
    U = []
    V = []

    for i in range(0,n):
        if i == 0:
            u = At[i]
            U.append(u)
            norm_u = norm(u)
            norm_list.append(norm_u)

        else:
            a = At[i]
            dp_list = []
            for j in range(0,i):
                dp = inner_product(a,U[j])
                dp_list.append(dp)

            u = []
            for j in range(0,n):
                val = a[j]
                for k in range(0, i):
                    val -= (dp_list[k] / norm_list[k]**2)*U[k][j]
                u.append(val)
            norm_u = norm(u)
            norm_list.append(norm_u)
            U.append(u)

        v = normalize(u)
        V.append(v)
    Q = transpose(V)

    R = []
    for i in range(0,n):
        r = []
        for j in range(0,n):
            if i > j:
                val = 0
                r.append(val)
            else:
                val = inner_product(At[j], V[i])
                r.append(val)
        R.append(r)
        
    return Q, R

from copy import deepcopy

def eig_qr(A):
    V = identity(len(A))
    for i in range(0,30):
        if i == 0:
            Ai = deepcopy(A)
        else:
            Ai = Ap
        Q, R = qr_gram(Ai)
        Ap = matmul(R,Q)
        V = matmul(V,Q)
    E = Ap
    return E, V #E=eigenvalue, V=eigenvector

def diag(A):
    m = len(A) # diagonal matrix is square matrix! -> m=n
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            if i != j:
                val = 0
                row.append(val)
            else:
                val = A[i][j]
                row.append(val)
        res.append(row)
    return res

In [16]:
# eigenvalue decomposition

A = [[1,2,3],[2,4,5],[3,5,3]]
E, V = eig_qr(A)
res = matmul(matmul(V, E), transpose(V)) # A = P﹒D﹒Pt
print(res) # A = res

[[1.0000000000000184, 1.9999999999999858, 3.000000000000059], [2.000000000000036, 3.9999999999999676, 4.999999999999968], [3.0000000000000564, 4.999999999999972, 3.0000000000000018]]


In [18]:
# eigenvalue decomposition using numpy

import numpy as np

A = np.array([[1,2,3],[2,4,5],[3,5,3]])
E, V = np.linalg.eig(A)
print(f"eigenvalue = {E}")
print(f"eigenvector = \n{V}")

eigenvalue = [ 9.90754321  0.05152112 -1.95906434]
eigenvector = 
[[-0.36762518 -0.82102902 -0.43676432]
 [-0.67017224  0.55950483 -0.48767152]
 [-0.64476422 -0.11342699  0.75591892]]


In [45]:
# singular value decomposition ****

def svd(A):
    At = transpose(A)
    AtA = matmul(At,A) # start from calculating At﹒A form!
    E, V = eig_qr(AtA)
    for i in range(len(E)):
        E[i][i] = E[i][i]**(0.5)
    S = diag(E)
    Vt = transpose(V)

    AV = matmul(A,V)
    AVt = transpose(AV)
    Ut= []
    for vector in AVt:
        Ut.append(normalize(vector))
    U = transpose(Ut)
    return U, S, Vt

# check!
B = [[3,6],[2,3],[1,2],[5,5]]
U,S,Vt = svd(B)
print(f"U = {U}\n")
print(f"Vt = {Vt}\n")
res = matmul(matmul(U,S),Vt)
print(res)

U = [[0.6305881956601931, 0.650700514117642], [0.34294607553087336, 0.07207639573280454], [0.21019606522006434, 0.21690017137254733], [0.6637500515540449, -0.7241188781987142]]

Vt = [[0.5811362175448531, 0.8138063016822007], [-0.8138063016822019, 0.5811362175448509]]

[[3.000000000000032, 5.999999999999975], [2.0000000000000098, 2.9999999999999933], [1.0000000000000104, 1.9999999999999913], [4.999999999999995, 5.000000000000007]]


In [33]:
# singular value decomposition using numpy *****

import numpy as np

B = [[3,6],[2,3],[1,2],[5,5]]

U,S,Vt = np.linalg.svd(B)

print(f"U={U}\n")
print(f"S={S}\n")
print(f"Vt={Vt}\n")

U=[[-0.6305882   0.65070051 -0.34404196  0.24613512]
 [-0.34294608  0.0720764   0.09856768 -0.93138466]
 [-0.21019607  0.21690017  0.9335582   0.19297931]
 [-0.66375005 -0.72411888 -0.01971354  0.18627693]]

S=[10.50804076  1.6065738 ]

Vt=[[-0.58113622 -0.8138063 ]
 [-0.8138063   0.58113622]]



In [39]:
import numpy as np

A = np.array([[3,6],[2,3],[1,2],[5,5]])
At = transpose(A)
AAt = matmul(A,At)
AtA = matmul(At,A)

E_1, V_1 = np.linalg.eig(AAt)
print(E_1)
E_2, V_2 = np.linalg.eig(AtA)
print(E_2)

[ 1.10418921e+02  2.58107939e+00 -1.70852282e-15  2.79986962e-15]
[  2.58107939 110.41892061]
