# Transposed Matrix

In [1]:
# transposed matrix
def transpose(A):
    m = len(A)
    n = len(A[0]) 
    
    res = []
    for j in range(n):
        row = []
        for i in range(m):
            row.append(A[i][j])
        res.append(row)
    return res

# transposed matrix: using numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
At1 = np.transpose(A)
print(At1)
At2 = A.T
print(At2)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


# Symmetric Matrix

In [36]:
# Symmetric Matrix Property 
import numpy as np

# If matrix A and transposed matrix At are same, then matrix A is symmetric.
A = np.array([[1,0,2],[0,2,1],[2,1,1]])
At = np.transpose(A)
A == At

# If matrix A is symmetric, then matrix A's nth degree matrix is always symmetric.
A = np.array([[1,0,2],[0,2,1],[2,1,1]])
AA = A
for i in range(9):
    AA = np.matmul(AA,A)
    print(f"matrix A's {i+2}th degree matrix:\n {AA}")

# For any matrix A, A﹒At and At﹒A are both always symmetric.
A = np.array([[1,0,2],[0,2,1],[2,1,1]])
At = np.transpose(A)
print(f"A﹒At =\n {np.matmul(A,At)}")
print(f"At﹒A =\n {np.matmul(At,A)}")

matrix A's 2th degree matrix:
 [[5 2 4]
 [2 5 3]
 [4 3 6]]
matrix A's 3th degree matrix:
 [[13  8 16]
 [ 8 13 12]
 [16 12 17]]
matrix A's 4th degree matrix:
 [[45 32 50]
 [32 38 41]
 [50 41 61]]
matrix A's 5th degree matrix:
 [[145 114 172]
 [114 117 143]
 [172 143 202]]
matrix A's 6th degree matrix:
 [[489 400 576]
 [400 377 488]
 [576 488 689]]
matrix A's 7th degree matrix:
 [[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
matrix A's 8th degree matrix:
 [[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
matrix A's 9th degree matrix:
 [[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
matrix A's 10th degree matrix:
 [[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]
A﹒At =
 [[5 2 4]
 [2 5 3]
 [4 3 6]]
At﹒A =
 [[5 2 4]
 [2 5 3]
 [4 3 6]]


# Diagonal Matrix

In [11]:
# diagonal matrix
def diag(A):
    m = len(A) # diagonal matrix is square matrix! -> m=n
    n = len(A[0])
    res = []
    for i in range(m):
        row = []
        for j in range(n):
            if i != j:
                val = 0
                row.append(val)
            else:
                val = A[i][j]
                row.append(val)
        res.append(row)
    return res

#diagonal element
def diag_ele(A):
    m = len(A)
    n = len(A[0])
    res = []
    for i in range(m):
        for j in range(n):
            if i == j:
                val = A[i][j]
                res.append(val)
    return res

# element to diagonal matrix
def ele2diag(a):
    res = []
    for i in range(len(a)):
        row = []
        for j in range(len(a)):
            if i == j:
                val = a[i]
                row.append(val)
            else:
                val = 0
                row.append(val)
        res.append(row)
    return res

In [14]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.diag(A)
print(D)
print(np.diag(D))

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [34]:
# properties of diagonal matrix

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.diag([1,3,4])

print(f"AD =\n {np.matmul(A,D)}")
print(f"DA =\n {np.matmul(D,A)}")

AD =
 [[ 1  6 12]
 [ 4 15 24]
 [ 7 24 36]]
DA =
 [[ 1  2  3]
 [12 15 18]
 [28 32 36]]


# Identity Matrix

In [5]:
# identity matrix

def identity(n):
    I = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                val = 1
                row.append(val)
            else:
                val = 0
                row.append(val)
        I.append(row)
    return I

In [33]:
import numpy as np
I = np.identity(3)
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
AI = np.matmul(A,I)
IA = np.matmul(I,A)
print(f"AI =\n {AI}")
print(f"IA =\n {IA}")

AI =
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
IA =
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Zero Matrix

In [20]:
# zero matrix

def zero_mat(n, p):
    Z = []
    for i in range(n):
        row = []
        for j in range(p):
            val = 0
            row.append(val)
        Z.append(row)
    return Z

In [20]:
import numpy as np
Z = np.zeros((3,2))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Triangular Matrix

In [28]:
# upper triangular matrix

def u_tri(A):
    utri = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            if i <= j:
                val = A[i][j]
                row.append(val)
            else:
                val = 0
                row.append(val)
        utri.append(row)
    return utri

# lower triangular matrix

def l_tri(A):
    ltri = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            if i >= j:
                val = A[i][j]
                row.append(val)
            else:
                val = 0
                row.append(val)
        ltri.append(row)
    return ltri

In [32]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Au = np.triu(A)
print(f"Upper triangular matrix:\n {Au}")
Al = np.tril(A)
print(f"Lower triangular matrix:\n {Al}")

Upper triangular matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower triangular matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


# Toeplitz Matrix *****

In [55]:
#toeplitz matrix

a = [1,0,-2,-4]
b = [1,3,5,7,9]

def toeplitz(a,b):
    n1 = len(a)
    n2 = len(b)
    A = []
    for i in range(n1):
        row = []
        for j in range(n2):
            if i <= j:
                row.append(b[j-i])
            else:
                row.append(a[i-j])
        A.append(row)
    return A

toeplitz(a,b)

[[1, 3, 5, 7, 9], [0, 1, 3, 5, 7], [-2, 0, 1, 3, 5], [-4, -2, 0, 1, 3]]

In [17]:
from scipy.linalg import toeplitz

A = toeplitz([1, 0,-2,-4], [1,3,5,7,9]) # a=[1,0,-2,-4], b=[1,3,5,7,9]
print(A)

[[ 1  3  5  7  9]
 [ 0  1  3  5  7]
 [-2  0  1  3  5]
 [-4 -2  0  1  3]]


# Bidiagonal Matrix

In [66]:
# upper bidiagonal matrix
def u_bidiag(A):
    n = len(A)
    m = len(A[0])
    res = []
    for i in range(n):
        row = []
        for j in range(m):
            if j-i < 0 or j-i > 1:
                val = 0
                row.append(val)
            else:
                val = A[i][j]
                row.append(val)
        res.append(row)
    return res

# lower bidiagonal matrix
def l_bidiag(A):
    n = len(A)
    m = len(A[0])
    res = []
    for i in range(n):
        row = []
        for j in range(m):
            if i-j < 0 or i-j > 1:
                val = 0
                row.append(val)
            else:
                val = A[i][j]
                row.append(val)
        res.append(row)
    return res

In [75]:
import numpy as np

# upper bidiagonal matrix
A = np.array([[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]])
diag_ele = np.diag(A)
u_diag_ele = np.diag(A,k=1)
u_diag = np.diag(diag_ele) + np.diag(u_diag_ele, k=1)
print(u_diag)

# lower bidiagonal matrix
A = np.array([[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]])
diag_ele = np.diag(A)
l_diag_ele = np.diag(A,k=-1)
l_diag = np.diag(diag_ele) + np.diag(l_diag_ele, k=-1)
print(l_diag)

[[1 2 0 0]
 [0 3 4 0]
 [0 0 7 9]
 [0 0 0 3]]
[[1 0 0 0]
 [5 3 0 0]
 [0 1 7 0]
 [0 0 1 3]]


# Householder Matrix

In [25]:
# outer product
def outer_product(a, b):
    n1 = len(a)
    n2 = len(b)
    res = []
    for i in range(n1):
        row = []
        for j in range(n2):
            val = a[i] * b[j]
            row.append(val)
        res.append(row)
    return res

# inner product
def inner_product(a, b):
    n1 = len(a) # n1 = len(b)
    val = 0
    for i in range(n1):
        val += a[i] * b[i]
    return val

# identity matrix
def identity(n):
    I = []
    for i in range(n):
        row = []
        for j in range(n):
            if i != j:
                val = 0
                row.append(val)
            else:
                val = 1
                row.append(val)
        I.append(row)
    return I

# matrix subtraction
def subtract(A, B):
    res = []
    for i in range(len(A)):
        row = []
        for j in range(len(B)):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

# householder matrix
def householder(v):
    n = len(v)
    outer_mat = outer_product(v,v) #list
    inner_val = inner_product(v,v) #int
    V = []
    for i in range(n):
        row = []
        for j in range(n):
            val = (outer_mat[i][j] / inner_val) * 2
            row.append(val)
        V.append(row)
    I = identity(n)
    H = subtract(I, V)
    return H    

In [34]:
import numpy as np

v = np.array([1,0,2,3])

n = len(v)
outer_mat = np.outer(v,v)
inner_val = np.inner(v,v)
I = np.identity(n)

H = I - (outer_mat/inner_val)*2